[workspace]
name = "swarm"
description = "Development environment for RoboStack ROS packages"
version = "0.1.0"
authors = ["Marcel Rath <marcel.rath@tum.de>", "Martin Schuck <martin.schuck@tum.de>"]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64"] 

[dependencies]
python = "<3.14" # MuJoCo has no wheels for Python 3.14
pip = "*"
uv = "*"
ruff = "*"
setuptools = "*"
# dependencies to build scipy
# TODO: Remove compilers once scipy 1.17 is released and drone-models have been updated.
cmake = "*"
gcc = "*"
cxx-compiler = "*"
gfortran = "*"
openblas = "*"

[target.linux.dependencies]
libgl-devel = "*"

[activation]
scripts = ["openai_api_key.sh"]

[environments]
# docs = { features = ["crazyflow", "docs"] }
# tests = { features = ["crazyflow", "tests"] }
sim = { features = ["crazyflow"], solve-group = "default"}
deploy = { features = ["ros_jazzy"] }

# docs feature
[feature.docs.dependencies]
mkdocs = ">=1.5.3"
mkdocs-material = ">=9.4.0"
mkdocstrings = ">=0.24.0"
mkdocstrings-python = ">=1.7.0"
mkdocs-gen-files = ">=0.5.0"
mkdocs-literate-nav = ">=0.6.0"

[feature.docs.tasks]
docs-serve = { cmd = "mkdocs serve", description = "Serve docs locally" }
docs-build = { cmd = "mkdocs build", description = "Build docs" }

# tests feature
[feature.tests.dependencies]
pytest = "*"

[feature.tests.tasks]
tests = { cmd = "pytest -v tests", description = "Run tests" }

# Crazyflow feature
[feature.crazyflow.pypi-dependencies]
swarm_gpt = { path = "./", editable = true }
crazyflow = { path = "../crazyflow", editable = true }
drone-models = { path = "../crazyflow/submodules/drone-models", editable = true }
drone-controllers = { path = "../crazyflow/submodules/drone-controllers", editable = true }
# axswarm = { git = "git@github.com:utiasDSL/axswarm.git" }
jax = { version = ">=0.7.0", extras = ["cuda"] }

# jazzy feature
[feature.ros_jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.ros_jazzy.activation] # install scripts
scripts = ["tools/setup_mocap.sh"]

[feature.ros_jazzy.dependencies]
python = ">=3.10"

ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"

compilers = "*"
cmake = "*"
openblas = "*"
pkg-config = "*"
make = "*"
ninja = "*"
rosbags = ">=0.10.9,<0.11"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "site-packages",
    "venv",
    "docs/conf.py",
]

line-length = 100
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "D", "TCH", "ANN"]
ignore = ["ANN401"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D100", "D103", "D104"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
suppress-dummy-args = true
suppress-none-returning = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"